---

- name: Create Downloads directory
  file:
    path: /home/vagrant/Downloads
    state: directory
    owner: vagrant

- name: Download Tor Browser package
  get_url:
    url: https://www.torproject.org/dist/torbrowser/13.0.6/tor-browser-linux-x86_64-13.0.6.tar.xz
    dest: /home/vagrant/Downloads/tor-browser-linux-x86_64-13.0.6.tar.xz
    mode: '500'
    checksum: sha512:3a5c0a17d01be98a79e29228a522d43d1f0cee4b52e98016259860dd2dcce2ba700bb6925693645e7846774f5fa53c11cd2cb7d94b21cd7bccf8debd358f62a8
    owner: vagrant

- name: Create Desktop directory
  file:
    path: /home/vagrant/Desktop
    state: directory
    owner: vagrant    

- name: Extract Tor Browser package
  unarchive:
    src: /home/vagrant/Downloads/tor-browser-linux-x86_64-13.0.6.tar.xz
    dest: /home/vagrant/Desktop
    remote_src: yes
    owner: vagrant
    mode: '700'
