---

- name: Upgrade packages for Debian-based hosts
  apt:
    update_cache: yes
    upgrade: dist
  run_once: yes
  when: ansible_distribution == 'Debian'
  tags:
    - upgrade
    - never

- name: Upgrade packages for CentOS-based hosts
  dnf:
    update_cache: yes
    upgrade: dist
  run_once: yes
  when: ansible_distribution == 'CentOS'
  tags:
    - upgrade
    - never
